version: "3.8"

services:
  app:
    image: panc1to/laravel-api:latest
    container_name: api-php
    env_file: /home/ec2-user/app/.env
    volumes:
      - /home/ec2-user/app/.env:/var/www/html/.env:ro
    expose:
      - "9000"
    networks:
      - api-network

  nginx:
    image: nginx:stable-alpine
    container_name: api-nginx
    ports:
      - "8000:80"
    volumes:
      - /home/ec2-user/app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - api-network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9001:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    networks:
      - api-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    networks:
      - api-network

networks:
  api-network:
    driver: bridge